# Generated by Django 5.2.3 on 2025-06-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='note',
        ),
    ]
