# Generated by Django 5.2.3 on 2025-07-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
