# Generated by Django 5.2.3 on 2025-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(max_length=99)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
