# Generated by Django 5.2.3 on 2025-07-14 06:47

import core.utilities.Upload_Path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.TextField(max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='', null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=core.utilities.Upload_Path.UploadPath)),
                ('fathers_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator'), ('assistant', 'Assistant'), ('instructor', 'Instructor')], default='student')),
            ],
            options={
                'verbose_name': 'AccountModel',
                'verbose_name_plural': 'AccountModels',
                'db_table': 'AccountModel',
                'ordering': ['name', 'gender', 'email', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(max_length=80)),
                ('profile_image', models.ImageField(upload_to=core.utilities.Upload_Path.UploadPath)),
                ('cover_image', models.ImageField(upload_to=core.utilities.Upload_Path.UploadPath)),
                ('available_sit', models.PositiveIntegerField()),
                ('assistant', models.ForeignKey(limit_choices_to={'role': 'assistant'}, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Assistant', to='Model_App.accountmodel')),
                ('coordinator', models.OneToOneField(limit_choices_to={'role': 'coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Coordinator', to='Model_App.accountmodel')),
                ('instructors', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Teacher', to='Model_App.accountmodel')),
            ],
            options={
                'verbose_name': 'CourseModel',
                'verbose_name_plural': 'CourseModels',
                'db_table': 'CourseModel',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DepertmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=30)),
                ('assistant', models.ManyToManyField(limit_choices_to={'role': 'assistant'}, related_name='Depertment_Assistant', to='Model_App.accountmodel')),
                ('coordinator', models.ForeignKey(limit_choices_to={'role': 'coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='Depertment_Head', to='Model_App.accountmodel')),
                ('instructors', models.ManyToManyField(limit_choices_to={'role': 'instructor'}, related_name='Depertment_Teacher', to='Model_App.accountmodel')),
            ],
            options={
                'verbose_name': 'DepertmentModel',
                'verbose_name_plural': 'DepertmentModels',
                'db_table': 'DepertmentModel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('subject_code', models.CharField(max_length=12, unique=True)),
                ('depertment', models.ManyToManyField(related_name='Course_Subject', to='Model_App.coursemodel')),
            ],
            options={
                'verbose_name': 'SubjectModel',
                'verbose_name_plural': 'SubjectModels',
                'db_table': 'SubjectModel',
                'ordering': ['title', 'subject_code'],
            },
        ),
    ]
