# Generated by Django 5.2.3 on 2025-07-13 19:02

import core.utilities.Upload_Path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Student', to='Model_App.coursemodel'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=core.utilities.Upload_Path.UploadPath),
        ),
    ]
