# Generated by Django 5.2.3 on 2025-07-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Model_App.accountmodel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model_App.coursemodel')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model_App.subjectmodel')),
            ],
            options={
                'verbose_name': 'StudentEnrollment',
                'verbose_name_plural': 'StudentEnrollments',
                'db_table': 'StudentEnrollment',
                'ordering': ['Student', 'course', 'subjects'],
            },
        ),
    ]
