# Generated by Django 5.2.4 on 2025-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator'), ('assistant', 'Assistant'), ('instructor', 'Instructor')], default='student', max_length=20),
        ),
    ]
