# Generated by Django 5.2.3 on 2025-07-13 19:03

import core.utilities.Upload_Path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_App', '0002_alter_accountmodel_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utilities.Upload_Path.UploadPath),
        ),
    ]
