# Generated by Django 5.2.3 on 2025-07-23 03:31

import core.utilities.Upload_Path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_App', '0002_studentenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utilities.Upload_Path.UploadPath),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utilities.Upload_Path.UploadPath),
        ),
    ]
