# Generated by Django 5.2.3 on 2025-07-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_App', '0004_alter_accountmodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='course',
            field=models.ForeignKey(default='cse', on_delete=django.db.models.deletion.CASCADE, related_name='Course_Student', to='Model_App.coursemodel'),
        ),
    ]
