# Generated by Django 5.2.3 on 2025-07-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField(max_length=99)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
