# Generated by Django 5.2.3 on 2025-07-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('student_id', models.IntegerField()),
                ('depertment', models.CharField()),
            ],
        ),
    ]
