# Generated by Django 5.2.3 on 2025-07-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseModel', '0002_studentmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='studentNote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BaseModel.studentmodels'),
        ),
    ]
