# Generated by Django 5.2.3 on 2025-07-02 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseModel', '0003_notes_studentnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='studentNote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseModel.studentmodels'),
        ),
    ]
